spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # 다른 IP에서도 접속 가능하도록 설정

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 838799738358-jl8sknrvlu1ct7okjpe7ddmt0qufbvke.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: capstone_muje
  secret_key: capstone_muje

frontend:
  base-url: "http://localhost:3000"

univcert:
  api-key: b2dbc1c6-3604-41fa-8bc9-5a36cc0f1dfc